---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    matchLabels:
      app: "nginx-1"
  ports:
  - name: abc
    protocol: TCP
    port: 80
    targetPort: http-web-svc
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-1"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-1"
  template:
    metadata:
      labels:
        app: "nginx-1"
    spec:
      containers:
      - name: "nginx-1"
        image: "nginx:latest"