name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker image
      run: |
        timestamp=$(date +%Y%m%d%H%M%S)
        docker build -t your-image-name:latest .
        docker tag your-image-name:latest your-image-name:${timestamp}
        docker push your-image-name:${timestamp}
    
      
